// 常量
// 断点续传压缩状态
const INCOMPRESSION = 0 // 压缩中
const FINISHCOMPRESSION = 1 // 成功结束
const ERRORCOMPRESSION = 2 // 出错

// 项目类型
const PROJECTTYPEISIPO = 100 // IPO及北交所上市
const PROJECTTYPEISREFINANCING = 110 // 再融资
const PROJECTTYPEISBOND = 120 // 债券
const PROJECTISMERGEREORGA = 140 // 并购重组
const PROJECTISNEWTHIRDBOARD = 160 // 新三板
const PROJECTTYPEISABS = 180 // ABS
const PROJECTTYPEISOTHERFINANCIAL = 200 // 其他财务顾问
const PROJECTTYPEISINVESTMENT = 220 // 投行引荐类

export default {
  INCOMPRESSION,
  FINISHCOMPRESSION,
  ERRORCOMPRESSION,
  PROJECTTYPEISIPO,
  PROJECTTYPEISREFINANCING,
  PROJECTTYPEISBOND,
  PROJECTISMERGEREORGA,
  PROJECTISNEWTHIRDBOARD,
  PROJECTTYPEISABS,
  PROJECTTYPEISOTHERFINANCIAL,
  PROJECTTYPEISINVESTMENT,
}
