name: Publish

on:
  push:
    branches:
      - main

jobs:
  publish:
    # To enable auto publishing to github, update your electron publisher
    # config in package.json > "build" and remove the conditional below
    if: ${{ github.repository_owner == 'GAJYA' }}

    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, macos-latest]

    steps:
      - name: Checkout git repo
        uses: actions/checkout@v3

      - name: Install Node and NPM
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm

      - name: 安装yarn
        run: npm i -g yarn

      - name: Install and build
        run: |
          yarn
          npm run package
        env:
          # This is used for uploading release assets to github
          GH_TOKEN: ${{ secrets.ACCESS_TOKEN }}

      - name: upload artifacts
        uses: actions/upload-artifact@v3.0.0
        with:
          name: ${{ matrix.os }}
          path: release/build

      - name: Publish releases
        uses: softprops/action-gh-release@v0.1.14
        if: startsWith(github.ref, 'refs/tags/')
        with:
            files: "release/build/**"
        env:
          # This is used for uploading release assets to github
          GH_TOKEN: ${{ secrets.ACCESS_TOKEN }}

